config/routes.rb
Rails.application.routes.draw do


  scope module: :public do
    root to: 'homes#top'
    get "/about" => "homes#about"
    resources :items, only: [:index, :show]
    resources :genres, only: [:show]
    resources :customers, only: [:show, :edit, :update]
    get 'customers/:id/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    patch 'customers/:id/withdrawal' => 'customers#withdrawal', as: 'withdrawal'
    resources :cart_items, only: [:index, :create, :update, :destroy] do
      collection do
        delete :destroy_all
      end
    end
    resources :orders, only: [:index, :show, :new, :create] do
      collection do
        get :thanks
        post :confirm
      end
    end
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end

  devise_for :customer, controllers: {
    sessions: 'public/devise/sessions',
    passwords: 'public/devise/passwords',
    registrations: 'public/devise/registrations'
  }


  namespace :admin do
    get "/" => "homes#top"
    resources :homes, only: [:show]
    resources :items, only: [:index, :show, :new, :create, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end

  devise_for :admin, controllers: {
    sessions: 'admin/devise/sessions',
  }



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, presence: true
  validates :prefecture_code, presence: true
  validates :address_city, presence: true
  validates :address_street, presence: true
  validates :telephone_number, presence: true



  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.all.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      flash[:success] = 'お客様情報を変更しました。'
      redirect_to admin_customer_path(@customer.id)
    else
      flash.now[:warning] = '必須項目に誤りがあります。必要情報を正しく入力してください。'
      render :edit
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name,
      :first_name,
      :last_name_kana,
      :first_name_kana,
      :postal_code,
      :prefecture_code,
      :address_city,
      :address_street,
      :address_building,
      :telephone_number,
      :email,
      :is_deleted,)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<script type="text/javascript" src="//jpostal-1006.appspot.com/jquery.jpostal.js"></script>

<h4><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集</h4>

  <%= form_with model: @customer, url: admin_customer_path(@customer.id), local: true do |f| %>

    <div class="form-group row">
      <div class="col-lg-1"></div>
      <div class="col-lg-2 px-0">会員ID</div>
      <div class="col-lg-1"></div>
      <div class="col-lg-8"><%= @customer.id %></div>
    </div>

    <div class="form-group row">
      <div class="col-lg-1"></div>
      <div class="col-lg-2 d-flex align-items-center px-0"><%= f.label :last_name, "氏名" %></div>
      <div class="col-lg-1 d-flex align-items-center justify-content-end px-0">(性)</div>
      <div class="col-lg-3"><%= f.text_field :last_name, class: "form-control" %></div>
      <div class="col-lg-1 text-right d-flex align-items-center justify-content-end px-0">(名)</div>
      <div class="col-lg-3"><%= f.text_field :first_name, class: "form-control" %></div>
    </div>

    <div class="form-group row">
      <div class="col-lg-1"></div>
      <div class="col-lg-2 d-flex align-items-center px-0"><%= f.label :last_name_kana, "フリガナ" %></div>
      <div class="col-lg-1 d-flex align-items-center justify-content-end px-0">(セイ)</div>
      <div class="col-lg-3"><%= f.text_field :last_name_kana, class: "form-control" %></div>
      <div class="col-lg-1 text-right d-flex align-items-center justify-content-end px-0">(メイ)</div>
      <div class="col-lg-3"><%= f.text_field :first_name_kana, class: "form-control" %></div>
    </div>

    <div class="form-group row">
      <div class="col-lg-1"></div>
      <div class="col-lg-2 px-0"><%= f.label :postal_code, "郵便番号" %></div>
      <div class="col-lg-1"></div>
      <div class="col-lg-3"><%= f.text_field :postal_code, class: "form-control" %></div>
    </div>

    <div class="form-group row">
      <div class="col-lg-1"></div>
      <div class="col-lg-2 d-flex align-items-center px-0">住所</div>
      <div class="col-lg-1 d-flex align-items-center justify-content-end px-0">(都道府県)</div>
      <div class="col-lg-3"><%= f.collection_select :prefecture_code, JpPrefecture::Prefecture.all, :code, :name, {}, {class: "form-control"} %></div>
      <div class="col-lg-1 d-flex align-items-center justify-content-end px-0">(市区町村)</div>
      <div class="col-lg-3"><%= f.text_field :address_city, class: "form-control" %></div>
    </div>

    <div class="form-group row">
      <div class="col-lg-3"></div>
      <div class="col-lg-1 d-flex align-items-center justify-content-end px-0">(町名番地)</div>
      <div class="col-lg-3"><%= f.text_field :address_street, class: "form-control" %></div>
    </div>

    <div class="form-group row">
      <div class="col-lg-3"></div>
      <div class="col-lg-1 d-flex align-items-center justify-content-end px-0">(建物名)</div>
      <div class="col-lg-7"><%= f.text_field :address_building, class: "form-control" %></div>
    </div>

    <div class="form-group row">
      <div class="col-lg-1"></div>
      <div class="col-lg-2 d-flex align-items-center px-0"><%= f.label :telephone_number, "電話番号" %></div>
      <div class="col-lg-1"></div>
      <div class="col-lg-3"><%= f.text_field :telephone_number, class: "form-control" %></div>
    </div>

    <div class="form-group row">
      <div class="col-lg-1"></div>
      <div class="col-lg-2 d-flex align-items-center px-0"><%= f.label :email, "メールアドレス" %></div>
      <div class="col-lg-1"></div>
      <div class="col-lg-3"><%= f.text_field :email, class: "form-control" %></div>
    </div>

    <div class="form-group row">
      <div class="col-lg-1"></div>
      <div class="col-lg-2 d-flex align-items-center px-0"><%= f.label :is_deleted, "会員ステータス" %></div>
      <div class="col-lg-1"></div>
      <div class="col-lg-3"><%= f.select :is_deleted,{有効:false, 退会:true}, {}, {class: "form-control"} %></div>
    </div>

    <div class="margin-straight"></div>

    <div class="actions row">
      <div class="col-lg-4"></div>
      <div class="col-lg-8"><%= f.submit '変更を保存', class:"btn btn-success btn-lg px-0 w-25" %></div>
    </div>


  <% end %>

app/views/admin/customers/index.html.erb
<h4>会員一覧</h4>

  <table class="table table-hover table-inverse margin-straight margin-side" style="width: 70%;">
    <thead>
      <tr>
        <th>会員ID</th>
        <th>氏名</th>
        <th>メールアドレス</th>
        <th>ステータス</th>
      </tr>
    </thead>

    <tbody>
      <% @customers.each do |customer| %>
        <tr>
          <td><%= customer.id %></td>
          <td>
            <%= link_to(admin_customer_path(customer.id)) do %>
            <%= customer.last_name%><%= customer.first_name %>
            <% end %>
          </td>
          <td><%= customer.email %></td>
          <% if customer.is_deleted == false %>
          <td class="text-success font-weight-bold">有効</td>
		      <% elsif customer.is_deleted == true %>
		      <td class="text-muted font-weight-bold">退会</td>
		      <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= paginate @customers %>

app/views/admin/customers/show.html.erb
<h4><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報</h4>

<table class="table table-borderless margin-left" style="width: 80%;">
	<tr>
	  <th style="width: 200px;">会員ID</th>
    <td><%= @customer.id %></td>
	</tr>

	<tr>
	  <th>氏名</th>
	  <td><%= @customer.last_name %>　<%= @customer.first_name %></td>
	</tr>

  <tr>
    <th>フリガナ</th>
    <td><%= @customer.last_name_kana %>　<%= @customer.first_name_kana %></td>
  </tr>

  <tr>
    <th>郵便番号</th>
	  <td><%= @customer.postal_code %></td>
	</tr>

   <tr>
    <th>住所</th>
    <td><%= @customer.prefecture_name %><%= @customer.address_city %><%= @customer.address_street %>　<%= @customer.address_building %></td>
  </tr>

	 <tr>
    <th>電話番号</th>
    <td><%= @customer.telephone_number %></td>
  </tr>

  <tr>
    <th>メールアドレス</th>
    <td><%= @customer.email %></td>
  </tr>

  <tr>
    <th>会員ステータス</th>
	  <% if @customer.is_deleted == false %>
    <td class="text-success font-weight-bold">有効</td>
	  <% elsif @customer.is_deleted == true %>
	  <td class="text-muted font-weight-bold">退会</td>
	  <% end %>
  </tr>
</table>


<table class="table table-borderless margin-left" style="width: 80%;">
	<tr>
		<th style="width: 200px;"></th>
    <td><%= link_to "編集する", edit_admin_customer_path(@customer), class:"btn btn-success px-0 w-50"%></td>
    <td><%= link_to "注文履歴一覧を見る", admin_home_path(@customer.id), class:"btn btn-primary px-0 w-50" %></td>
  </tr>
</table>