config/routes.rb
Rails.application.routes.draw do


  scope module: :public do
    root to: 'homes#top'
    get "/about" => "homes#about"
    resources :items, only: [:index, :show]
    resources :genres, only: [:show]
    resources :customers, only: [:show, :edit, :update]
    get 'customers/:id/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    patch 'customers/:id/withdrawal' => 'customers#withdrawal', as: 'withdrawal'
    resources :cart_items, only: [:index, :create, :update, :destroy] do
      collection do
        delete :destroy_all
      end
    end
    resources :orders, only: [:index, :show, :new, :create] do
      collection do
        get :thanks
        post :confirm
      end
    end
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end

  devise_for :customer, controllers: {
    sessions: 'public/devise/sessions',
    passwords: 'public/devise/passwords',
    registrations: 'public/devise/registrations'
  }


  namespace :admin do
    get "/" => "homes#top"
    resources :homes, only: [:show]
    resources :items, only: [:index, :show, :new, :create, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end

  devise_for :admin, controllers: {
    sessions: 'admin/devise/sessions',
  }



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord

  validates :customer_id, presence: true
  validates :postal_code_item, presence: true
  validates :prefecture_code_item, presence: true
  validates :address_city_item, presence: true
  validates :address_street_item, presence: true
  validates :address_building_item, presence: true
  validates :name_item, presence: true
  validates :postage, presence: true
  validates :payment, presence: true
  validates :total_amount, presence: true
  validates :order_status, presence: true


  belongs_to :customer
  has_many :order_details, dependent: :destroy


  enum payment: { credit_card: 0, transfer: 1 }
  enum order_status: { waiting_payment: 0, payment_confirmation: 1, in_production: 2, shipping_preparation: 3, shipped: 4 }


end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def show
    @order = Order.find(params[:id])
    @sum_item_price_purchase = 0
  end

  def update
    @order = Order.find(params[:id])
    @order_details = @order.order_details.all
    if @order.update(order_params)
      flash[:success] = '注文ステータスを更新しました。'
      if @order.order_status == Order.order_statuses.key(1)
        @order_details.each do |order_detail|
          order_detail.create_status = OrderDetail.create_statuses.key(1)
          order_detail.save
          flash[:notice] = '製作ステータスが変更されました。'
        end
      end
      redirect_to admin_order_path(@order.id)
    else
      flash.now[:danger] = 'エラーが発生し、更新できませんでした。'
      render :show
    end
  end

  private

  def order_params
    params.require(:order).permit(:order_status)
  end

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<h4>注文履歴詳細</h4>

  <div class="form-group row">
    <div class="col-lg-2">購入者</div>
    <div class="col-lg-10">
      <%= link_to(admin_customer_path(@order.customer_id)) do %>
        <%= @order.customer.last_name %><%= @order.customer.first_name %>
      <% end %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-lg-2">注文日</div>
    <div class="col-lg-10"><%= @order.created_at.strftime('%Y/%m/%d') %></div>
  </div>

  <div class="form-group row">
    <div class="col-lg-2">配送先</div>
    <div class="col-lg-10">
      〒<%= @order.postal_code_item %>
      <%= @order.prefecture_name_item %><%= @order.address_city_item %><%= @order.address_street_item %>
      <%= @order.address_building_item %><br>
      <%= @order.name_item %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-lg-2">支払方法</div>
    <div class="col-lg-10"><%= @order.payment_i18n %></div>
  </div>

  <%= form_with model: @order, url: admin_order_path(@order.id), local: true do |f| %>
  <div class="form-group actions row">
    <div class="col-lg-2 d-flex align-items-center">注文ステータス</div>
    <div class="col-lg-2 d-flex align-items-center">
      <%= f.select :order_status, Order.order_statuses.keys.map {|k|[I18n.t("enums.order.order_status.#{k}"), k]}, {}, {class: "form-control center"} %>
    </div>
    <div class="col-lg-1"><%= f.submit '更新', class:"btn btn-success px-3" %></div>
    <div class="col-lg-7"></div>
  </div>
  <% end %>

  <div class="row mt-5">

    <table class="table table-hover table-inverse col-lg-8">
      <thead>
        <tr>
          <th>商品名</th>
          <th>単価（税込）</th>
          <th>数量</th>
          <th>小計</th>
          <th>製作ステータス</th>
          <th style="width: 90px;"></th>
        </tr>
      </thead>

      <tbody>
        <% @order.order_details.all.each do |order_detail| %>
          <%= form_with model: order_detail, url: admin_order_detail_path(order_detail.id), local: true do |f| %>
          <tr>
            <td class="align-middle"><%= order_detail.item.name %></td>
            <td class="align-middle">　<%= order_detail.price_purchase.to_s(:delimited, delimiter: ',') %></td>
            <td class="align-middle">　<%= order_detail.amount %></td>
            <% @sum_item_price_purchase += order_detail.subtotal_tax_price_purchase %>
            <td class="align-middle"><%= order_detail.subtotal_tax_price_purchase.to_s(:delimited, delimiter: ',') %></td>
            <td class="align-middle">
              <%= f.select :create_status, OrderDetail.create_statuses.keys.map {|k|[I18n.t("enums.order_detail.create_status.#{k}"), k]}, {}, {class: "form-control center"} %>
            </td>
            <td class="align-middle"><%= f.submit '更新', class:"btn btn-success px-3 " %></td>
          </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>

    <table class="table table-borderless col-lg-3 d-flex align-items-end justify-content-end">
	     <tr>
	       <th style="width: 130px;">商品合計</th>
	       <td><%= @sum_item_price_purchase.to_s(:delimited, delimiter: ',')  %>円</td>
	     </tr>

	     <tr>
	       <th>送料</th>
	       <td><%= @order.postage.to_s(:delimited, delimiter: ',') %>円</td>
	     </tr>

	     <tr>
	       <th>請求金額合計</th>
	       <td class="font-weight-bold"><%= @order.total_amount.to_s(:delimited, delimiter: ',') %>円</td>
	     </tr>
    </table>

    <div class="col-lg-1"></div>

  </div>