config/routes.rb
Rails.application.routes.draw do


  scope module: :public do
    root to: 'homes#top'
    get "/about" => "homes#about"
    resources :items, only: [:index, :show]
    resources :genres, only: [:show]
    resources :customers, only: [:show, :edit, :update]
    get 'customers/:id/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    patch 'customers/:id/withdrawal' => 'customers#withdrawal', as: 'withdrawal'
    resources :cart_items, only: [:index, :create, :update, :destroy] do
      collection do
        delete :destroy_all
      end
    end
    resources :orders, only: [:index, :show, :new, :create] do
      collection do
        get :thanks
        post :confirm
      end
    end
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end

  devise_for :customer, controllers: {
    sessions: 'public/devise/sessions',
    passwords: 'public/devise/passwords',
    registrations: 'public/devise/registrations'
  }


  namespace :admin do
    get "/" => "homes#top"
    resources :homes, only: [:show]
    resources :items, only: [:index, :show, :new, :create, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end

  devise_for :admin, controllers: {
    sessions: 'admin/devise/sessions',
  }



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord

  validates :name, presence: true
  validates :postal_code, presence: true
  validates :prefecture_code, presence: true
  validates :address_city, presence: true
  validates :address_street, presence: true



  def full_address
    ['〒', postal_code, '　', prefecture_name, address_city, address_street, address_building, '　', name].join('')
  end


  belongs_to :customer

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  include JpPrefecture
  jp_prefecture :prefecture_code

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end

  def prefecture_name_item
    JpPrefecture::Prefecture.find(code: prefecture_code_item).try(:name)
  end

  def prefecture_name_item=(prefecture_name)
    self.prefecture_code_item = JpPrefecture::Prefecture.find(name: prefecture_name_item).code
  end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  validates :item_id, presence: true
  validates :customer_id, presence: true
  validates :amount, presence: true

  belongs_to :customer
  belongs_to :item

  def subtotal_tax_price
    item.add_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, presence: true
  validates :prefecture_code, presence: true
  validates :address_city, presence: true
  validates :address_street, presence: true
  validates :telephone_number, presence: true



  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy

end

app/models/genre.rb
class Genre < ApplicationRecord
  validates :name, presence: true
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord

  validates :genre_id, presence: true
  validates :name, presence: true
  validates :image, presence: true
  validates :introduction, presence: true
  validates :price, presence: true

  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  attachment :image

  def add_tax_price
    (self.price * 1.10).round
  end
end

app/models/order.rb
class Order < ApplicationRecord

  validates :customer_id, presence: true
  validates :postal_code_item, presence: true
  validates :prefecture_code_item, presence: true
  validates :address_city_item, presence: true
  validates :address_street_item, presence: true
  validates :address_building_item, presence: true
  validates :name_item, presence: true
  validates :postage, presence: true
  validates :payment, presence: true
  validates :total_amount, presence: true
  validates :order_status, presence: true


  belongs_to :customer
  has_many :order_details, dependent: :destroy


  enum payment: { credit_card: 0, transfer: 1 }
  enum order_status: { waiting_payment: 0, payment_confirmation: 1, in_production: 2, shipping_preparation: 3, shipped: 4 }


end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  validates :order_id, presence: true
  validates :item_id, presence: true
  validates :amount, presence: true
  validates :price_purchase, presence: true
  validates :create_status, presence: true

  belongs_to :item
  belongs_to :order

  def subtotal_tax_price_purchase
    price_purchase * amount
  end

  enum create_status: { cannot_start: 0, waiting_production: 1, in_production: 2, complete_production: 3 }

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    @orders = Order.all.page(params[:page]).reverse_order
  end

  def show
    @customer = Customer.find(params[:id])
    @orders = Order.where(customer_id: @customer.id).page(params[:page]).reverse_order
  end

  private

  def order_params
    params.require(:order).permit(:order_status)
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @items = Item.page(params[:page])
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:success] = "#{@item.name}を新規登録しました。"
      redirect_to admin_item_path(@item.id)
    else
      flash.now[:danger] = 'エラーが発生し、登録できませんでした。'
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:success] = '変更を保存しました。'
      redirect_to admin_item_path(@item.id)
    else
      flash.now[:warning] = '必須項目に誤りがあります。必要情報を正しく入力してください。'
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :image, :introduction, :price, :genre_id, :is_active)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:
      [:last_name,
      :first_name,
      :last_name_kana,
      :first_name_kana,
      :postal_code,
      :prefecture_code,
      :address_city,
      :address_street,
      :address_building,
      :telephone_number,
      :email,
      :is_active,
      :created_at,
      :updated_at])
  end

  add_flash_types :success, :info, :warning, :danger

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin_homes_helper.rb
module AdminHomesHelper
end

app/helpers/admin_items_helper.rb
module AdminItemsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    case flash_type
      when "success"
      "success"
      when "error"
      "danger"
      when "alert"
      "warning"
      when "notice"
      "info"
      else
      flash_type.to_s
    end
  end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/homes/show.html.erb
  <h4><%= @customer.last_name + @customer.first_name %>さんの注文履歴一覧</h4>

  <table class="table table-hover table-inverse margin-straight field">
    <thead>
      <tr>
        <th>購入日時</th>
        <th>購入者</th>
        <th>注文個数</th>
        <th>注文ステータス</th>
      </tr>
    </thead>

    <tbody>
      <% @orders.each do |order| %>
        <% @sum_amount = 0 %>
        <tr>
          <td><%= link_to order.created_at.strftime('%Y/%m/%d %H:%M:%S'), admin_order_path(order.id) %></td>
          <td><%= order.customer.last_name + order.customer.first_name %></td>
          <td>
            <% order.order_details.all.each do |order_detail| %>
              <% @sum_amount += order_detail.amount %>
            <% end %>
            <%= @sum_amount %>
          </td>
          <td><%= order.order_status_i18n %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= paginate @orders %>

  <div class="center mt-5">
    <%= link_to "全会員の注文履歴一覧に戻る", admin_path, class:"btn btn-primary px-0 w-25" %>
  </div>

app/views/admin/homes/top.html.erb
  <h4>注文履歴一覧</h4>

  <table class="table table-hover table-inverse margin-straight field">
    <thead>
      <tr>
        <th>購入日時</th>
        <th>購入者</th>
        <th>注文個数</th>
        <th>注文ステータス</th>
      </tr>
    </thead>

    <tbody>
      <% @orders.each do |order| %>
        <% @sum_amount = 0 %>
        <tr>
          <td><%= link_to order.created_at.strftime('%Y/%m/%d %H:%M:%S'), admin_order_path(order.id) %></td>
          <td><%= link_to order.customer.last_name + order.customer.first_name, admin_home_path(order.customer_id) %></td>
          <td>
            <% order.order_details.all.each do |order_detail| %>
              <% @sum_amount += order_detail.amount %>
            <% end %>
            <%= @sum_amount %>
          </td>
          <td><%= order.order_status_i18n %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= paginate @orders %>

app/views/admin/items/edit.html.erb
<h4>商品編集</h4>

  <%= form_with model: @item, url: admin_item_path(@item.id), local: true do |f| %>

  <div class="field">
    <div class="form-group row">
      <div class="col-lg-1"></div>
      <div class="col-lg-3 d-flex align-items-center"><%= f.label :image, "商品画像" %></div>
      <div class="col-lg-7"><%= f.attachment_field :image %></div>
      <div class="col-lg-1"></div>
    </div>

    <div class="form-group row">
      <div class="col-lg-1"></div>
      <div class="col-lg-3 d-flex align-items-center"><%= f.label :name, "商品名" %></div>
      <div class="col-lg-7"><%= f.text_field :name, class: "form-control" %></div>
      <div class="col-lg-1"></div>
    </div>

    <div class="form-group row">
      <div class="col-lg-1"></div>
      <div class="col-lg-3"><%= f.label :introduction, "商品説明" %></div>
      <div class="col-lg-7"><%= f.text_area :introduction, class: "form-control" %></div>
      <div class="col-lg-1"></div>
    </div>

    <div class="form-group row">
      <div class="col-lg-1"></div>
      <div class="col-lg-3 d-flex align-items-center"><%= f.label :genre_id, "ジャンル" %></div>
      <div class="col-lg-7"><%= f.collection_select :genre_id, Genre.all, :id, :name, {include_blank: "選択して下さい"}, {class: "form-control"} %></div>
      <div class="col-lg-1"></div>
    </div>

    <div class="form-group row">
      <div class="col-lg-1"></div>
      <div class="col-lg-3 d-flex align-items-center"><%= f.label :price, "税抜価格" %></div>
      <div class="col-lg-7"><%= f.text_field :price, class: "form-control" %></div>
      <div class="col-lg-1 d-flex align-items-center">円</div>
    </div>

    <div class="form-group row">
      <div class="col-lg-1"></div>
      <div class="col-lg-3 d-flex align-items-center"><%= f.label :is_active, "販売ステータス" %></div>
      <div class="col-lg-7"><%= f.select :is_active,{販売中:true, 販売停止中:false}, {}, {class: "form-control"} %></div>
      <div class="col-lg-1"></div>
    </div>

    <div class="actions center">
      <%= f.submit '変更を保存', class:"btn btn-success btn-lg px-0 w-25" %>
    </div>
  </div>

  <% end %>

app/views/admin/items/index.html.erb
<div class="d-flex justify-content-between align-items-center">

  <h4>商品一覧</h4>
  <%= link_to '＋', new_admin_item_path, class:"btn btn-lg rounded-circle p-0" %>

</div>

  <table class="table table-hover table-inverse margin-straight field">
    <thead>
      <tr>
        <th>商品ID</th>
        <th>商品名</th>
        <th>税抜価格</th>
        <th>ジャンル</th>
        <th>ステータス</th>
      </tr>
    </thead>

    <tbody>
      <% @items.each do |item| %>
        <tr>
          <td><%= item.id %></td>
          <td><%= link_to item.name, admin_item_path(item.id) %></td>
          <td><%= item.price %></td>
          <td><%= item.genre.name %></td>
          <% if item.is_active == true %>
          <td class="text-success font-weight-bold">販売中</td>
		      <% elsif item.is_active == false %>
		      <td class="text-muted font-weight-bold">販売停止中</td>
		      <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= paginate @items %>

app/views/admin/items/new.html.erb
<h4>商品新規登録</h4>

  <%= form_with model: @item, url: admin_items_path, local: true do |f| %>

  <div class="field">
    <div class="form-group row">
      <div class="col-lg-1"></div>
      <div class="col-lg-3 d-flex align-items-center"><%= f.label :image, "商品画像" %></div>
      <div class="col-lg-7"><%= f.attachment_field :image %></div>
      <div class="col-lg-1"></div>
    </div>

    <div class="form-group row">
      <div class="col-lg-1"></div>
      <div class="col-lg-3 d-flex align-items-center"><%= f.label :name, "商品名" %></div>
      <div class="col-lg-7"><%= f.text_field :name, class: "form-control" %></div>
      <div class="col-lg-1"></div>
    </div>

    <div class="form-group row">
      <div class="col-lg-1"></div>
      <div class="col-lg-3"><%= f.label :introduction, "商品説明" %></div>
      <div class="col-lg-7"><%= f.text_area :introduction, class: "form-control" %></div>
      <div class="col-lg-1"></div>
    </div>

    <div class="form-group row">
      <div class="col-lg-1"></div>
      <div class="col-lg-3 d-flex align-items-center"><%= f.label :genre_id, "ジャンル" %></div>
      <div class="col-lg-7"><%= f.collection_select :genre_id, Genre.all, :id, :name, {include_blank: "選択して下さい"}, {class: "form-control"} %></div>
      <div class="col-lg-1"></div>
    </div>

    <div class="form-group row">
      <div class="col-lg-1"></div>
      <div class="col-lg-3 d-flex align-items-center"><%= f.label :price, "税抜価格" %></div>
      <div class="col-lg-7"><%= f.text_field :price, class: "form-control" %></div>
      <div class="col-lg-1 d-flex align-items-center">円</div>
    </div>

    <div class="form-group row">
      <div class="col-lg-1"></div>
      <div class="col-lg-3 d-flex align-items-center"><%= f.label :is_active, "販売ステータス" %></div>
      <div class="col-lg-7"><%= f.select :is_active,{販売中:true, 販売停止中:false}, {}, {class: "form-control"} %></div>
      <div class="col-lg-1"></div>
    </div>

    <div class="actions center">
      <%= f.submit '新規登録', class:"btn btn-success btn-lg px-0 w-25" %>
    </div>
  </div>

  <% end %>

app/views/admin/items/show.html.erb
<h4>商品詳細</h4>

<div class="row" style="width: 90%; margin: 0px auto;">
  <div class="col-lg-5 image_size">
    <%= attachment_image_tag @item, :image %>
  </div>
  <div class="col-lg-7">
    <table class="table table-borderless" style="width: 500px;">
	  <tr>
	    <th style="width: 150px;">商品名</th>
	    <td><%= @item.name %></td>
	  </tr>

	  <tr>
	    <th>商品説明</th>
	    <td><%= @item.introduction %></td>
	  </tr>

	  <tr>
	    <th>ジャンル</th>
	    <td><%= @item.genre.name %></td>
	  </tr>

	  <tr>
      <th>税込価格<br>(税抜価格)</br></th>
	    <td class="d-flex align-items-center"><%= @item.add_tax_price.to_s(:delimited) %>   (<%= @item.price %>)  円</td>
	  </tr>

	  <tr>
	    <th>販売ステータス</th>
		<% if @item.is_active == true %>
        <td class="text-success font-weight-bold">販売中</td>
		<% elsif @item.is_active == false %>
		<td class="text-muted font-weight-bold">販売停止中</td>
		<% end %>
		</td>
	  </tr>
	  </table>
  </div>
</div>

<div class="center">
  <%= link_to "編集する", edit_admin_item_path(@item), class:"btn btn-success px-0 w-25" %>
</div>