config/routes.rb
Rails.application.routes.draw do


  scope module: :public do
    root to: 'homes#top'
    get "/about" => "homes#about"
    resources :items, only: [:index, :show]
    resources :genres, only: [:show]
    resources :customers, only: [:show, :edit, :update]
    get 'customers/:id/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    patch 'customers/:id/withdrawal' => 'customers#withdrawal', as: 'withdrawal'
    resources :cart_items, only: [:index, :create, :update, :destroy] do
      collection do
        delete :destroy_all
      end
    end
    resources :orders, only: [:index, :show, :new, :create] do
      collection do
        get :thanks
        post :confirm
      end
    end
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end

  devise_for :customer, controllers: {
    sessions: 'public/devise/sessions',
    passwords: 'public/devise/passwords',
    registrations: 'public/devise/registrations'
  }


  namespace :admin do
    get "/" => "homes#top"
    resources :homes, only: [:show]
    resources :items, only: [:index, :show, :new, :create, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end

  devise_for :admin, controllers: {
    sessions: 'admin/devise/sessions',
  }



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord

  validates :name, presence: true
  validates :postal_code, presence: true
  validates :prefecture_code, presence: true
  validates :address_city, presence: true
  validates :address_street, presence: true



  def full_address
    ['〒', postal_code, '　', prefecture_name, address_city, address_street, address_building, '　', name].join('')
  end


  belongs_to :customer

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  include JpPrefecture
  jp_prefecture :prefecture_code

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end

  def prefecture_name_item
    JpPrefecture::Prefecture.find(code: prefecture_code_item).try(:name)
  end

  def prefecture_name_item=(prefecture_name)
    self.prefecture_code_item = JpPrefecture::Prefecture.find(name: prefecture_name_item).code
  end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  validates :item_id, presence: true
  validates :customer_id, presence: true
  validates :amount, presence: true

  belongs_to :customer
  belongs_to :item

  def subtotal_tax_price
    item.add_tax_price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, presence: true
  validates :prefecture_code, presence: true
  validates :address_city, presence: true
  validates :address_street, presence: true
  validates :telephone_number, presence: true



  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy

end

app/models/genre.rb
class Genre < ApplicationRecord
  validates :name, presence: true
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord

  validates :genre_id, presence: true
  validates :name, presence: true
  validates :image, presence: true
  validates :introduction, presence: true
  validates :price, presence: true

  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  attachment :image

  def add_tax_price
    (self.price * 1.10).round
  end
end

app/models/order.rb
class Order < ApplicationRecord

  validates :customer_id, presence: true
  validates :postal_code_item, presence: true
  validates :prefecture_code_item, presence: true
  validates :address_city_item, presence: true
  validates :address_street_item, presence: true
  validates :address_building_item, presence: true
  validates :name_item, presence: true
  validates :postage, presence: true
  validates :payment, presence: true
  validates :total_amount, presence: true
  validates :order_status, presence: true


  belongs_to :customer
  has_many :order_details, dependent: :destroy


  enum payment: { credit_card: 0, transfer: 1 }
  enum order_status: { waiting_payment: 0, payment_confirmation: 1, in_production: 2, shipping_preparation: 3, shipped: 4 }


end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  validates :order_id, presence: true
  validates :item_id, presence: true
  validates :amount, presence: true
  validates :price_purchase, presence: true
  validates :create_status, presence: true

  belongs_to :item
  belongs_to :order

  def subtotal_tax_price_purchase
    price_purchase * amount
  end

  enum create_status: { cannot_start: 0, waiting_production: 1, in_production: 2, complete_production: 3 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:
      [:last_name,
      :first_name,
      :last_name_kana,
      :first_name_kana,
      :postal_code,
      :prefecture_code,
      :address_city,
      :address_street,
      :address_building,
      :telephone_number,
      :email,
      :is_active,
      :created_at,
      :updated_at])
  end

  add_flash_types :success, :info, :warning, :danger

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin_homes_helper.rb
module AdminHomesHelper
end

app/helpers/admin_items_helper.rb
module AdminItemsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    case flash_type
      when "success"
      "success"
      when "error"
      "danger"
      when "alert"
      "warning"
      when "notice"
      "info"
      else
      flash_type.to_s
    end
  end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <header class="border-bottom border-dark">
        <nav class="navbar navbar-expand-lg navbar-light">
          <a class="navbar-brand" href="/">
            <span>ながのCAKE</span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse row" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">

            <% if customer_signed_in? %>

            <li class="nav-item col-lg-3 text-center">
              <%= link_to "マイページ", customer_path(current_customer.id), class: 'nav-link text-dark border rounded' %>
            </li>

            <li class="nav-item col-lg-3 text-center">
              <%= link_to "商品一覧", items_path, class: 'nav-link text-dark border rounded' %>
            </li>

            <li class="nav-item col-lg-3 text-center">
              <%= link_to "カート", cart_items_path, class: 'nav-link text-dark border rounded' %>
            </li>

            <li class="nav-item col-lg-3 text-center">
              <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'nav-link text-dark border rounded' %>
            </li>

            <% elsif admin_signed_in? %>

            <li class="nav-item col-lg-2 text-center"></li>
            <li class="nav-item col-lg-2 text-center">
              <%= link_to "商品一覧", admin_items_path, class: 'nav-link text-dark border rounded' %>
            </li>
            <li class="nav-item col-lg-2 text-center">
              <%= link_to "会員一覧", admin_customers_path, class: 'nav-link text-dark border rounded' %>
            </li>
            <li class="nav-item col-lg-2 text-center">
              <%= link_to "注文履歴一覧", admin_path, class: 'nav-link text-dark border rounded' %>
            </li>
            <li class="nav-item col-lg-2 text-center">
              <%= link_to "ジャンル一覧", admin_genres_path, class: 'nav-link text-dark border rounded' %>
            </li>
            <li class="nav-item col-lg-2 text-center">
              <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link text-dark border rounded' %>
            </li>

            <% else %>

            <li class="nav-item col-lg-3 text-center">
              <%= link_to "About", about_path, class: 'nav-link text-dark border rounded' %>
            </li>
            <li class="nav-item col-lg-3 text-center">
              <%= link_to "商品一覧", items_path, class: 'nav-link text-dark border rounded' %>
            </li>
            <li class="nav-item col-lg-3 text-center">
              <%= link_to "新規登録", new_customer_registration_path, class: 'nav-link text-dark border rounded' %>
            </li>
            <li class="nav-item col-lg-3 text-center">
              <%= link_to "ログイン", new_customer_session_path, class: 'nav-link text-dark border rounded' %>
            </li>

            <% end %>
            </ul>
          </div>
        </nav>
      </header>

      <main>
        <% flash.each do |message_type, message| %>
          <div class="center alert alert-<%= bootstrap_class_for(message_type) %>">
            <%= message %>
          </div>
        <% end %>

        <%= yield %>

      </main>

    </div>
  </body>
</html>